[mypy]
python_version = 3.11
files = backend/core, backend/api, backend/services, backend/schemas, backend/db
ignore_missing_imports = True
follow_imports = skip
show_error_codes = True
warn_redundant_casts = True
warn_unused_ignores = True
check_untyped_defs = False
disallow_untyped_defs = False
pretty = True

[mypy-tests.*]
ignore_errors = True